---
title: "Initial analysis"
author: "Courtney Hilton"
date: "11/02/2021"
output: html_document
---


Oooh, should look at - https://cjvanlissa.github.io/tidySEM/

also - https://lmudge13.github.io/sample_code/likert_graphs.html


```{r load_libs_and_data, include=FALSE}
# Set default .rmd parameters
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, echo = FALSE)

# Load libraries
library(pacman)
p_load(tidyverse,
       patchwork,
       readxl,
       here,
       ggtext)

# Load raw data (questionnaire results)
raw_data <- read_excel(here::here("data", "questionnaire_results.xlsx"))

# Custom plotting theme
custom_theme <- theme_bw() + 
  theme(panel.grid.minor.x = element_blank(),
        legend.title = element_text(size = 12),
        legend.text = element_text(color = "grey30"),
        plot.title = element_text(size = 18, face = "bold"))

```

```{r clean_data}
# create vector of question names
question_items <- colnames(raw_data)[8:38]

# removing random escaped characters
question_items <- gsub("\n","",question_items,fixed=T)
question_items <- gsub("\r","",question_items,fixed=T)

# rename covariates
data1 <- raw_data %>% 
  as_tibble() %>% 
  select(1:7) %>% 
  rename(
     above_18 = 1,
     username = 2, 
     age = 3, 
     gender = 4, 
     country = 5,
     how_often_play_chess = 6,
     how_often_study_chess = 7) 

# rename question columns
data2 <- raw_data %>% 
  as_tibble() %>% 
  select(8:40) %>% 
  rename(Q = 1:31,
         date_completed = 32,
         token = 33)

# combine
data_clean <- bind_cols(data1,data2)
# remove temp variables
rm(data1,data2)

# Checking that all participants are over 18: YES THEY ARE
# unique(data_clean$above_18)
# removing that column
data_clean <- select(data_clean, -above_18)



data_clean$how_often_play_chess <- factor(data_clean$how_often_play_chess, 
                                          levels = c("Less than once per week",
                                                     "Once per week",
                                                     "Two times per week",
                                                     "More than three times per week",
                                                     "Everyday"))

data_clean$how_often_study_chess <- factor(data_clean$how_often_study_chess, 
                                          levels = c("Less than once per week",
                                                     "Once per week",
                                                     "Two times per week",
                                                     "More than three times per week",
                                                     "Everyday"))

```


```{r ages_plot}

ggplot(data_clean,
       aes(x = age, fill = gender)) +
  geom_histogram(stat = "count") + 
  labs(title = "Who are our survey respondants?", 
       x = "Age (years)", y = "# participants") +
  custom_theme + 
  theme(panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = 'grey', 
                                          linetype = 'dotted'),
        panel.grid.minor.y = element_line(color = 'grey', 
                                          linetype = 'dotted'))

```

```{r countries_plot}

countries <- data_clean %>% 
  count(country) %>% 
  arrange(desc(n)) %>% 
  add_row(country = "combined countries with < 10 participants", n = sum(.$n <= 10))


ggplot(filter(countries, n > 10),
       aes(x = reorder(country, n), y = n)) +
  geom_bar(stat='identity', fill = "purple") +
  guides(fill = FALSE) +
  coord_flip() + 
  labs(title = "Where do our participants come from?",
       y = "# participants", 
       x = "Countries") +
  custom_theme

```


```{r chess_engagement_plot}

# how often play chess
play_plot <- ggplot(data_clean,
       aes(x = how_often_play_chess)) +
  geom_histogram(stat = "count", fill = "#0350df") + 
  coord_flip() +
  labs(title = "How often do they <i style='color:#0350df;'>play</i> chess?", 
       x = "", y = "# participants") +
  custom_theme + 
  theme(plot.title = ggtext::element_markdown())

# how often study chess 
study_plot <- ggplot(data_clean,
       aes(x = how_often_study_chess)) +
  geom_histogram(stat = "count", fill = "#d8000c") + 
  coord_flip() +
  labs(title = "How often do they <i style='color:#d8000c;'>study</i> chess?", 
       x = "", y = "# participants") +
  custom_theme +
  theme(plot.title = ggtext::element_markdown())

play_plot / study_plot

```

```{r questionnaire_plots}

```



