---
title: "Initial analysis"
author: "Courtney Hilton"
date: "11/02/2021"
output: 
  html_document:
    theme: lumen
---

```{r rmd_params}

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, echo = FALSE, fig.align = "center")

```


```{r load_libraries}

library(pacman)
p_load(tidyverse,
       patchwork,
       readxl,
       here,
       ggtext,
       likert)
#Oooh, should look at - https://cjvanlissa.github.io/tidySEM/
#also - https://lmudge13.github.io/sample_code/likert_graphs.html

```

```{r load_data}

# checks if preprocessed data exists, if not: runs script
# (!!you should also run script if you have updated the data)
if (!file.exists(here("data", "preprocessed_questionnaire.RData"))) {
  source(here("analysis", "preprocessing_questionnaire.R"))
}

# Load preprocessed data
load(here("data", "preprocessed_questionnaire.RData"))

```



```{r custom_plotting_themes}

# create clean custom theme
custom_theme <- theme_bw() + 
  theme(panel.grid.minor.x = element_blank(),
        legend.title = element_text(size = 12),
        legend.text = element_text(color = "grey30"),
        plot.title = element_text(size = 18, face = "bold"))

# set as default
theme_set(custom_theme)

```


```{r ages_plot}

ggplot(data_clean,
       aes(x = age, fill = gender)) +
  geom_histogram(stat = "count") + 
  labs(title = "Who are our survey respondants?", 
       x = "Age (years)", y = "# participants") +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = 'grey', 
                                          linetype = 'dotted'),
        panel.grid.minor.y = element_line(color = 'grey', 
                                          linetype = 'dotted'))

```

```{r countries_plot}

countries <- data_clean %>% 
  count(country) %>% 
  arrange(desc(n)) %>% 
  add_row(country = "combined countries with < 10 participants", n = sum(.$n <= 10))


ggplot(filter(countries, n > 10),
       aes(x = reorder(country, n), y = n)) +
  geom_bar(stat='identity', fill = "purple") +
  guides(fill = FALSE) +
  coord_flip() + 
  labs(title = "Where are they from?",
       y = "# participants", 
       x = "")


```


```{r chess_engagement_plot}

# how often play chess
play_plot <- ggplot(data_clean,
       aes(x = how_often_play_chess)) +
  geom_histogram(stat = "count", fill = "#0350df") + 
  coord_flip() +
  labs(title = "How often do they <i style='color:#0350df;'>play</i> chess?", 
       x = "", y = "# participants") +
  theme(plot.title = ggtext::element_markdown())

# how often study chess 
study_plot <- ggplot(data_clean,
       aes(x = how_often_study_chess)) +
  geom_histogram(stat = "count", fill = "#d8000c") + 
  coord_flip() +
  labs(title = "How often do they <i style='color:#d8000c;'>study</i> chess?", 
       x = "", y = "# participants") +
  theme(plot.title = ggtext::element_markdown())

play_plot / study_plot

```


# Questionnaire responses **ordered** by agreement

```{r likert_plots, fig.width = 8, fig.height = 20}

item_plots <- plot(likert(questions_named), wrap = 30, clip = "off")

item_plots
```








